### ISSUE TITLE
Criar o Roadmap

### ISSUE THREAD

**Issue by JoaoSchmitz** [fga-eps-mds/2022-1-PokeRanking#51]
## Descrição

Realizar a criação do Roadmap da Release 1 do projeto.

## Tarefas

- [x] Escolher um dos templates decididos em #12
- [x] Realizar a criação do Roadmap para a Release 1.

## Critérios de Aceitação

- [x] Subir o Roadmap finalizado para o repositório.

## Informação adicional

O Figma pode ser utilizado como ferramenta de criação.
